apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: database-persistent-volume-claim 
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  volumeName: database-persistent-volume