apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment 
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server 
    spec:
      containers: 
        - name: server 
          image: shol/server 
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_HOSTNAME
              value: mongo-cluster-ip-service
            - name: MONGO_PORT
              value: '27017'
            - name: MONGO_DB
              value: mschool
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-username 
                  key: MONGO_USERNAME
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-password
                  key: MONGO_PASSWORD
