apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment 
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server 
    spec:
      restartPolicy: Always
      initContainers:
        - name: wait-for-init-db
          image: busybox
          command: ['sh', '-c', 'until nc -z
          mongo-cluster-ip-service:27017; do echo waiting for db; sleep 2; done;']
      containers: 
        - name: server 
          image: shol/server 
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_HOSTNAME
              value: mongo-cluster-ip-service
            - name: MONGO_PORT
              value: '27017'
            - name: MONGO_DB
              value: dbfornewproject
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-username 
                  key: MONGO_USERNAME
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-password
                  key: MONGO_PASSWORD
